### ISSUE TITLE
flake8 test failed with error `F821 undefined name Keyboard

### ISSUE THREAD

**Issue by tigran-saatchyan** [skypro-008/electronics-shop-project#55]
### Resources
[homework-5/main.py](https://github.com/skypro-008/electronics-shop-project/blob/main/homework-5/main.py)

### Action Items
-  `kb = KeyBoard('Dark Project KD87A', 9600, 5)`
- - `F821 undefined name 'KeyBoard'`

### Caused by
`from src.keyboard import Keyboard (line 1)`

### Suggested corrective action
-  `kb = Keyboard('Dark Project KD87A', 9600, 5)`

**Comment by kirillskyeng** [comment]
Fixed. Thanks!
